import { Router, type IRouter } from "express";
import healthRouter from "./health";
import authRouter from "./auth";
import incubatorsRouter from "./incubators";
import foundersRouter from "./founders";
import sprintsRouter from "./sprints";
import emailsRouter from "./emails";
import calendarRouter from "./calendar";
import summaryRouter from "./summary";
import googleRouter from "./google";
import adminImportRouter from "./admin-import";
import aiAutomationRouter from "./ai-automation";
import companiesRouter from "./companies";
import companyEmailsRouter from "./companyEmails";
import dashboardStatsRouter from "./dashboardStats";
import researchWorkspaceRouter from "./researchWorkspace";
import globalSearchRouter from "./globalSearch";
import sprintSessionsRouter from "./sprintSessions";
import outcomesReportRouter from "./outcomesReport";
import builderRouter from "./builderRoutes";
import summaryBuilderRouter from "./summaryBuilderRoutes";
import tSheetRouter from "./tSheet";
import preSprintRouter from "./preSprint";

const router: IRouter = Router();

router.use(healthRouter);
router.use(authRouter);
router.use(incubatorsRouter);
router.use(foundersRouter);
router.use(sprintsRouter);
router.use(emailsRouter);
router.use(calendarRouter);
router.use(summaryRouter);
router.use(googleRouter);
router.use(adminImportRouter);
router.use(aiAutomationRouter);
router.use(companiesRouter);
router.use(companyEmailsRouter);
router.use(dashboardStatsRouter);
router.use(researchWorkspaceRouter);
router.use(globalSearchRouter);
router.use(sprintSessionsRouter);
router.use(outcomesReportRouter);
router.use(builderRouter);
router.use(summaryBuilderRouter);
router.use(tSheetRouter);
router.use(preSprintRouter);

export default router;
